// Líderes
export const LIDERES_OBTENIDOS='LIDERES_OBTENIDOS';
export const CARGANDO_LIDERES='CARGANDO_LIDERES';
export const ERROR_LIDERES='ERROR_LIDERES';

// Niveles
export const NIVELES_OBTENIDOS='NIVELES_OBTENIDOS';
export const CARGANDO_NIVELES='CARGANDO_NIVELES';
export const ERROR_NIVELES='ERROR_NIVELES';

// Modalidades
export const MODALIDADES_OBTENIDAS='MODALIDADES_OBTENIDAS';
export const CARGANDO_MODALIDADES='CARGANDO_MODALIDADES';
export const ERROR_MODALIDADES='ERROR_MODALIDADES';

// Usuario
export const USUARIO_OBTENIDO='USUARIO_OBTENIDO';
export const CARGANDO_USUARIO='CARGANDO_USUARIO';
export const ERROR_USUARIO='ERROR_USUARIO';

// Cursos
export const CURSOS_OBTENIDOS='CURSOS_OBTENIDOS';
export const CARGANDO_CURSOS='CARGANDO_CURSOS';
export const ERROR_CURSOS='ERROR_CURSOS';

// Registro
export const REGISTRO_USUARIO_EXITOSO='REGISTRO_USUARIO_EXITOSO';
export const CARGANDO_REGISTRO_USUARIO='CARGANDO_REGISTRO_USUARIO';
export const ERROR_REGISTRO_USUARIO='ERROR_REGISTRO_USUARIO';

// Búsqueda profesores
export const PROFESORES_OBTENIDOS_BUSQUEDA='PROFESORES_OBTENIDOS_BUSQUEDA';
export const CARGANDO_PROFESORES_BUSQUEDA='CARGANDO_PROFESORES_BUSQUEDA';
export const ERROR_PROFESORES_BUSQUEDA='ERROR_PROFESORES_BUSQUEDA';

// Búsqueda profesores desde chatBot
export const PROFESORES_OBTENIDOS_BUSQUEDA_CHATBOT='PROFESORES_OBTENIDOS_BUSQUEDA_CHATBOT';
export const CARGANDO_PROFESORES_BUSQUEDA_CHATBOT='CARGANDO_PROFESORES_BUSQUEDA_CHATBOT';
export const ERROR_PROFESORES_BUSQUEDA_CHATBOT='ERROR_PROFESORES_BUSQUEDA_CHATBOT';

// Perfil
export const PERFIL_OBTENIDO='PERFIL_OBTENIDO';
export const CARGANDO_PERFIL='CARGANDO_PERFIL';
export const ERROR_PERFIL='ERROR_PERFIL';

// Pestana perfil contrato (local)
export const SELECCIONAR_PESTANA_PERFIL_CONTRATO='SELECCIONAR_PESTANA_PERFIL_CONTRATO';

// Pasos contrato (local)
export const ESTABLECER_PASO_CONTRATO='ESTABLECER_PASO_CONTRATO';

// Contrato (local)
export const ESTABLECER_DATOS_CONTRATO='ESTABLECER_DATOS_CONTRATO';

// Registro publicacion
export const REGISTRANDO_PUBLICACION='REGISTRANDO_PUBLICACION';
export const PUBLICACION_REGISTRADA='PUBLICACION_REGISTRADA';
export const ERROR_REGISTRO_PUBLICACION='ERROR_REGISTRO_PUBLICACION';

// Registro contrato
export const REGISTRANDO_CONTRATO='REGISTRANDO_CONTRATO';
export const CONTRATO_REGISTRADO='CONTRATO_REGISTRADO';
export const ERROR_REGISTRO_CONTRATO='ERROR_REGISTRO_CONTRATO';

// Inicio sesión
export const INICIANDO_SESION='INICIANDO_SESION';
export const SESION_INICIADA='SESION_INICIADA';
export const SESION_NO_INICIADA='SESION_NO_INICIADA';

// Actualización de horarios del profesor
export const ACTUALIZANDO_HORARIOS='ACTUALIZANDO_HORARIOS';
export const HORARIOS_ACTUALIZADOS='HORARIOS_ACTUALIZADOS';
export const ERROR_ACTUALIZACION_HORARIOS='ERROR_ACTUALIZACION_HORARIOS';

// Chatbot
export const ENVIANDO_MENSAJE_CHATBOT='ENVIANDO_MENSAJE_CHATBOT';
export const RESPUESTA_RECIBIDA_CHATBOT='RESPUESTA_RECIBIDA_CHATBOT';
export const ERROR_MENSAJE_CHATBOT='ERROR_MENSAJE_CHATBOT';