// Líderes
export const LIDERES_OBTENIDOS='LIDERES_OBTENIDOS';
export const CARGANDO_LIDERES='CARGANDO_LIDERES';
export const ERROR_LIDERES='ERROR_LIDERES';

// Niveles
export const NIVELES_OBTENIDOS='NIVELES_OBTENIDOS';
export const CARGANDO_NIVELES='CARGANDO_NIVELES';
export const ERROR_NIVELES='ERROR_NIVELES';

// Modalidades
export const MODALIDADES_OBTENIDAS='MODALIDADES_OBTENIDAS';
export const CARGANDO_MODALIDADES='CARGANDO_MODALIDADES';
export const ERROR_MODALIDADES='ERROR_MODALIDADES';

// Usuario
export const USUARIO_OBTENIDO='USUARIO_OBTENIDO';
export const CARGANDO_USUARIO='CARGANDO_USUARIO';
export const ERROR_USUARIO='ERROR_USUARIO';

// Cursos
export const CURSOS_OBTENIDOS='CURSOS_OBTENIDOS';
export const CARGANDO_CURSOS='CARGANDO_CURSOS';
export const ERROR_CURSOS='ERROR_CURSOS';

// Registro
export const REGISTRO_USUARIO_EXITOSO='REGISTRO_USUARIO_EXITOSO';
export const CARGANDO_REGISTRO_USUARIO='CARGANDO_REGISTRO_USUARIO';
export const ERROR_REGISTRO_USUARIO='ERROR_REGISTRO_USUARIO';

// Búsqueda profesores
export const PROFESORES_OBTENIDOS_BUSQUEDA='PROFESORES_OBTENIDOS_BUSQUEDA';
export const CARGANDO_PROFESORES_BUSQUEDA='CARGANDO_PROFESORES_BUSQUEDA';
export const ERROR_PROFESORES_BUSQUEDA='ERROR_PROFESORES_BUSQUEDA';

// Perfil
export const PERFIL_OBTENIDO='PERFIL_OBTENIDO';
export const CARGANDO_PERFIL='CARGANDO_PERFIL';
export const ERROR_PERFIL='ERROR_PERFIL';

// Inicio sesión
export const INICIANDO_SESION='INICIANDO_SESION';
export const SESION_INICIADA='SESION_INICIADA';
export const SESION_NO_INICIADA='SESION_NO_INICIADA';
